# Generated by Django 4.2.7 on 2023-11-05 16:29

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('photo', models.FileField(upload_to='', validators=[myapp.validators.validate_file_size])),
                ('date', models.DateField()),
                ('telegram', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('aboutuser', models.TextField()),
            ],
        ),
    ]
